language: node_js
node_js:
  - 7.9.0

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  
script:
  - ng build --prod
  - bash ./.build.sh
  
before_deploy:
  - cd dist
  
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: pradnyamankar@yahoo.com
  password: Persistent@123
  organization: Persistent Sys L
  space: dev
  on:
    branch: master
