language: node_js
node_js:
- 7.9.0
branches:
  only:
  - master
before_script:
- npm install
script:
#- ng build
- npm run test:once
- npm run e2e
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup: true
  api: https://api.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  app: ChatApp
  on:
    repo: PradnyaM14/ChatApp