language: node_js
node_js:
- 7.9.0
branches:
  only:
  - master
before_script:
- npm install
script:
- ng build
before_deploy:
- cd dist
deploy:
  edge: true
  skip_cleanup: true
  manifest: manifest.yml
  provider: bluemixcloudfoundry
  api: https://api.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  
  on:
    repo: PradnyaM14/ChatApp
    branch: master
