dist: trusty
sudo: required
os: linux
language: node_js
node_js:
- 7.9.0
env:
  global:
  - CF_APP=ChatApp
branches:
  only:
  - master
before_script:
- npm install
script:
- ng build
before_deploy:
- cd dist
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup: true
  api: https://api.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  app: ChatApp
  on:
    repo: PradnyaM14/ChatApp
    condition: $TRAVIS_OS_NAME = linux